# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               Myo͞o
tagline:             ' ‒ Just another programming blog'
description:         'Myo͞o'
url:                 http://halfo.github.io
baseurl:             http://halfo.github.io/
paginate:            4

# About/contact
author:
  name:              Hasib Billah
  url:               https://github.com/halfo
  email:             hasib.7724@gmail.com

# Custom vars
version:             1.0.0
