# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tool Toul To
tagline:             ' ‒ A programming blog'
url:                 http://halfo.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Hasib Billah
  url:               https://github.com/halfo
  email:             hasib.7724@gmail.com

# Custom vars
version:             1.0.0
